<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-10T14:15:26 IST" name="Default suite" finished-at="2025-10-10T14:15:37 IST" duration-ms="10460">
    <groups>
    </groups>
    <test started-at="2025-10-10T14:15:26 IST" name="Default test" finished-at="2025-10-10T14:15:37 IST" duration-ms="10460">
      <class name="FederalBank_TestCases.TC12_ReinstatingTheDocumentaryCredit">
        <test-method is-config="true" signature="setup()[pri:0, instance:FederalBank_TestCases.TC12_ReinstatingTheDocumentaryCredit@5be1d0a4]" started-at="2025-10-10T14:15:26 IST" name="setup" finished-at="2025-10-10T14:15:28 IST" duration-ms="1773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="runTest()[pri:0, instance:FederalBank_TestCases.TC12_ReinstatingTheDocumentaryCredit@5be1d0a4]" started-at="2025-10-10T14:15:28 IST" name="runTest" finished-at="2025-10-10T14:15:37 IST" duration-ms="8434" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[❌ Assertion Failure: Test failed: E3664 - Verification Pending in [A] Option]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ❌ Assertion Failure: Test failed: E3664 - Verification Pending in [A] Option
at org.testng.Assert.fail(Assert.java:111)
at FederalBank_TestCases.TC12_ReinstatingTheDocumentaryCredit.runTest(TC12_ReinstatingTheDocumentaryCredit.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTest -->
      </class> <!-- FederalBank_TestCases.TC12_ReinstatingTheDocumentaryCredit -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
