<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [CombinedTestSuite]">
  <test thread-count="5" name="CombinedTests(failed)">
    <classes>
      <class name="CASA.Cashdeposit">
        <methods>
          <include name="addcashdeposit"/>
          <include name="setup"/>
          <include name="tearDown"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- CASA.Cashdeposit -->
      <class name="CASA.CreateSavingsAccount">
        <methods>
          <include name="createAccount" invocation-numbers="0"/>
          <include name="tearDown"/>
          <include name="setup"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- CASA.CreateSavingsAccount -->
      <class name="CASA.VerificationOfSavingsAccount">
        <methods>
          <include name="VerifySBAccount"/>
          <include name="setup"/>
          <include name="tearDown"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- CASA.VerificationOfSavingsAccount -->
    </classes>
  </test> <!-- CombinedTests(failed) -->
</suite> <!-- Failed suite [CombinedTestSuite] -->
